# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/bioconda/linux-64/bbmap-37.66-0.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/bowtie2-2.3.3.1-py27pl5.22.0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.6-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.11.5-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2017.11.5-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/curl-7.54.1-0.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/freebayes-1.1.0.46-htslib1.6_2.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/htslib-1.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.14.2-0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgcc-7.2.0-h69d50b8_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgcc-ng-7.2.0-h7cc24e2_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libssh2-1.8.0-1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libstdcxx-ng-7.2.0-h7a57d05_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-5.9-10.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openjdk-8.0.121-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.0.2m-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/perl-5.22.0.1-0.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/picard-2.15.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pip-9.0.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-2.7.14-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-6.2-0.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/samtools-1.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-38.2.3-py27_0.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/snpeff-4.3.1r-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.13.0-1.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/tbb-4.4_20150728-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.5.19-2.tar.bz2
https://conda.anaconda.org/bioconda/linux-64/vcftools-0.1.15-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.30.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.8-3.tar.bz2
